# Generated by Django 3.1.7 on 2021-03-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogPage',
        ),
    ]
