# Generated by Django 3.1.7 on 2021-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindsApp', '0002_auto_20210318_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='dynamicPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('logo', models.ImageField(upload_to='blog/')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
