# Generated by Django 3.1.7 on 2021-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindsApp', '0003_dynamicpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpage',
            name='image',
            field=models.ImageField(upload_to='media/blog/'),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='logo',
            field=models.ImageField(upload_to='media/blog/'),
        ),
    ]
