# Generated by Django 3.1.7 on 2021-03-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindsApp', '0004_auto_20210325_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpage',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='logo',
            field=models.ImageField(upload_to='blog/'),
        ),
    ]
