# Generated by Django 3.1.7 on 2021-03-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindsApp', '0006_auto_20210325_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliderPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('logo', models.ImageField(upload_to='slider/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
